import { test, expect } from '@playwright/test'
import { CLAUDE, LABELS, PI, browseUrl, nodeBody, openGraph, waitForApi } from './helpers.ts'

test.beforeEach(async ({ request }) => { await waitForApi(request) })

for (const returnAction of ['button', 'history'] as const) {
  test(`return via ${returnAction} survives a listing deletion while the graph is unmounted`, async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await openGraph(page, browseUrl('Pi', PI))
    await page.getByRole('button', { name: 'Expand Claude', exact: true }).click()
    await page.getByRole('button', { name: `Expand ${LABELS[CLAUDE]}`, exact: true }).click()
    await expect(nodeBody(page, `Pi/${PI}/workflow.md`)).toBeVisible()
    await page.getByRole('button', { name: 'Outline', exact: true }).click()
    // Simulate the post-deletion listing without modifying a seeded file.
    await page.route('**/api/entries', async route => {
      const response = await route.fetch()
      const body = await response.json() as { locations: unknown[]; entries: Array<{ source: string; locationId: string; path: string }> }
      await route.fulfill({ json: { locations: body.locations, entries: body.entries.filter(entry => !(entry.locationId === PI && entry.path === 'workflow.md')) } })
    })
    await page.getByRole('button', { name: 'Refresh', exact: true }).click()
    const outline = page.getByRole('navigation', { name: 'Directory outline' })
    await expect(outline.locator(`[data-node-id="Pi/${PI}/workflow.md"]`)).toHaveCount(0)
    const remaining = outline.locator(`[data-node-id="Claude/${CLAUDE}/workflow.md"] .outline-name`)
    await remaining.click()
    await expect(page.getByRole('tabpanel')).toContainText('Sample Claude workflow')
    if (returnAction === 'button') await page.getByRole('button', { name: 'Back to folder' }).click()
    else await page.goBack()
    await expect(outline).toBeVisible()
    await expect(remaining).toBeFocused()
    await page.getByRole('button', { name: 'Outline', exact: true }).click()
    await expect(nodeBody(page, `Claude/${CLAUDE}/workflow.md`)).toBeVisible()
    await expect(nodeBody(page, `Pi/${PI}/workflow.md`)).toHaveCount(0)
    expect(errors).toEqual([])
  })
}

test('reload discards the document origin even when history.state contains a prior browsing snapshot', async ({ page }) => {
  await openGraph(page, browseUrl('Claude', CLAUDE))
  await page.getByRole('button', { name: 'Expand Pi', exact: true }).click()
  await page.getByRole('button', { name: `Expand ${LABELS[PI]}`, exact: true }).click()
  await nodeBody(page, `Pi/${PI}/workflow.md`).click()
  await expect(page.getByRole('tabpanel')).toContainText('Sample Pi workflow')
  await page.reload()
  await expect(page.getByRole('tabpanel')).toContainText('Sample Pi workflow')
  await page.getByRole('button', { name: 'Back to folder' }).click()
  await expect(page).toHaveURL(browseUrl('Pi', PI))
})

test('native Back saves the departing browsing entry and Forward restores its latest mode and expansion', async ({ page }) => {
  await openGraph(page, browseUrl('Pi', PI))
  await nodeBody(page, `Pi/${PI}/workflow.md`).click()
  await expect(page.getByRole('tabpanel')).toContainText('Sample Pi workflow')
  await page.getByRole('button', { name: 'Back to folder' }).click()
  await page.getByRole('button', { name: 'Outline', exact: true }).click()
  const outline = page.getByRole('navigation', { name: 'Directory outline' })
  await outline.getByRole('button', { name: 'Expand skills', exact: true }).click()
  await page.goBack()
  await expect(page.getByRole('tabpanel')).toContainText('Sample Pi workflow')
  await page.goForward()
  await expect(outline).toBeVisible()
  await expect(outline.getByRole('button', { name: 'Collapse skills', exact: true })).toBeVisible()
})

test('historical outline origin restores its own scroll, focus and expansion after another origin changes them', async ({ page }) => {
  await page.setViewportSize({ width: 600, height: 420 })
  await openGraph(page, browseUrl('Claude', CLAUDE))
  await page.getByRole('button', { name: 'Outline', exact: true }).click()
  const outline = page.getByRole('navigation', { name: 'Directory outline' })
  await outline.getByRole('button', { name: 'Expand Pi', exact: true }).click()
  await outline.getByRole('button', { name: `Expand ${LABELS[PI]}`, exact: true }).click()
  await outline.getByRole('button', { name: 'Expand skills', exact: true }).click()
  await outline.getByRole('button', { name: 'Expand subagents', exact: true }).click()
  const file = outline.locator(`[data-node-id="Claude/${CLAUDE}/workflow.md"] .outline-name`)
  await file.focus()
  await outline.evaluate(element => { element.scrollTop = element.scrollHeight })
  const scroll = await outline.evaluate(element => element.scrollTop)
  expect(scroll).toBeGreaterThan(0)
  await file.press('Enter')
  await expect(page.getByRole('tabpanel')).toContainText('Sample Claude workflow')
  await page.getByRole('button', { name: 'Back to folder' }).click()
  await outline.getByRole('button', { name: 'Collapse Pi', exact: true }).click()
  await outline.evaluate(element => { element.scrollTop = 0 })
  await outline.locator('[data-node-id="Pi"] > .outline-row > .outline-name').click()
  await file.click()
  await expect(page.getByRole('tabpanel')).toContainText('Sample Claude workflow')
  await page.goBack()
  await expect(page).toHaveURL('/browse/Pi')
  await page.goBack()
  await expect(page).toHaveURL(browseUrl('Claude', CLAUDE))
  await page.goBack()
  await expect(page.getByRole('tabpanel')).toContainText('Sample Claude workflow')
  await page.getByRole('button', { name: 'Back to folder' }).click()
  await expect(page).toHaveURL(browseUrl('Claude', CLAUDE))
  await expect(file).toBeFocused()
  await expect(outline.getByRole('button', { name: 'Collapse Pi', exact: true })).toBeVisible()
  expect(await outline.evaluate(element => element.scrollTop)).toBe(scroll)
})

test('Back between browsing entries restores each graph viewport, and Forward retains changes made before native Back', async ({ page }) => {
  await openGraph(page, browseUrl('Pi', PI))
  const graphView = () => page.locator('.graph-canvas > g').getAttribute('transform')
  const first = await graphView()
  await nodeBody(page, 'Claude').click()
  await page.getByRole('button', { name: 'Zoom out' }).click()
  const second = await graphView()
  expect(second).not.toBe(first)
  await page.goBack()
  await expect(page).toHaveURL(browseUrl('Pi', PI))
  await expect(page.locator('.graph-canvas > g')).toHaveAttribute('transform', first!)
  await page.goForward()
  await expect(page).toHaveURL('/browse/Claude')
  await expect(page.locator('.graph-canvas > g')).toHaveAttribute('transform', second!)
})
