import { test, expect, type Page } from '@playwright/test'
import { randomUUID } from 'node:crypto'
import { mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { expandButton, node, nodeBody, openGraph, waitForApi } from './helpers.ts'

const fixtureRoot = fileURLToPath(new URL('../fixtures/', import.meta.url))
const created: string[] = []

/** Every test works inside its own scratch folders (one per source), removed recursively afterwards. */
async function scratchFolders() {
  const name = `scratch-${randomUUID().slice(0, 8)}`
  const pi = join(fixtureRoot, 'pi', name)
  const claude = join(fixtureRoot, 'claude', name)
  created.push(pi, claude)
  await mkdir(pi)
  await mkdir(claude)
  return { name, pi, claude }
}

async function exists(path: string) {
  try { await stat(path); return true } catch { return false }
}

test.beforeEach(async ({ request }) => { await waitForApi(request) })
test.afterEach(async () => {
  for (const path of created.splice(0)) await rm(path, { recursive: true, force: true })
})

const dialog = (page: Page) => page.getByRole('dialog')
const outcome = (page: Page) => page.getByTestId('operation-outcome')
const editButton = (page: Page) => page.getByRole('button', { name: 'Edit', exact: true })
const editor = (page: Page) => page.locator('.cm-content')

async function typeAtEnd(page: Page, text: string) {
  await editor(page).click()
  await page.keyboard.press('Control+End')
  await page.keyboard.type(text)
}

test('New file in the selected folder validates the name, prevents double submit, shows server conflicts, then opens the file', async ({ page }) => {
  const scratch = await scratchFolders()
  await writeFile(join(scratch.pi, 'taken.md'), 'taken')
  await openGraph(page, `/Pi/${scratch.name}`)
  await expect(node(page, `Pi/${scratch.name}`)).toHaveClass(/is-selected/)

  const posts: string[] = []
  page.on('request', request => { if (request.method() === 'POST' && request.url().includes('/api/mutate')) posts.push(request.postData() ?? '') })
  await page.getByRole('button', { name: 'New file…' }).click()
  const form = dialog(page)
  await expect(form).toContainText(`Pi / ${scratch.name}`)
  const name = form.getByRole('textbox', { name: 'File name' })
  await name.fill('notes.txt')
  await form.getByRole('button', { name: 'Create' }).click()
  await expect(form.getByRole('alert')).toContainText('.md')
  await name.fill('a/b.md')
  await form.getByRole('button', { name: 'Create' }).click()
  await expect(form.getByRole('alert')).toContainText('/')
  expect(posts).toHaveLength(0)

  await name.fill('taken.md')
  await form.getByRole('button', { name: 'Create' }).click()
  await expect(form.getByRole('alert')).toContainText('already exists')
  expect(posts).toHaveLength(1)
  await expect(form).toBeVisible()

  // Double submit: while the request is pending the button is disabled and only one request goes out.
  let release: () => void = () => {}
  const held = new Promise<void>(resolve => { release = resolve })
  await page.route('**/api/mutate', async route => { await held; await route.continue() })
  await name.fill('fresh.md')
  const create = form.getByRole('button', { name: 'Create' })
  await create.click()
  await expect(create).toBeDisabled()
  await create.click({ force: true })
  await page.keyboard.press('Enter')
  await page.waitForTimeout(200)
  expect(posts).toHaveLength(2)
  const completed = page.waitForResponse(response => response.url().includes('/api/mutate'))
  release()
  await completed
  await page.unroute('**/api/mutate')

  await expect(page).toHaveURL(`/file/Pi/${scratch.name}/fresh.md`)
  await expect(page.getByRole('heading', { level: 2, name: 'fresh.md' })).toBeVisible()
  await expect(page.getByRole('tabpanel')).toContainText('This file is empty.')
  expect(await readFile(join(scratch.pi, 'fresh.md'), 'utf8')).toBe('')
  await expect(outcome(page)).toContainText('Created fresh.md')
  await page.getByRole('button', { name: 'Back to folder' }).click()
  await expect(node(page, `Pi/${scratch.name}/fresh.md`)).toBeVisible()
  await expect(node(page, `Pi/${scratch.name}/taken.md`)).toBeVisible()
})

test('New folder reveals and selects the folder; unrelated expansion and pins are kept', async ({ page }) => {
  const scratch = await scratchFolders()
  await openGraph(page, `/Pi/${scratch.name}`)
  await expandButton(page, 'Claude').click()
  await expect(node(page, 'Claude/subagents')).toBeVisible()
  await nodeBody(page, 'Claude/subagents').focus()
  await page.keyboard.press('p')
  await expect(node(page, 'Claude/subagents')).toHaveClass(/is-pinned/)

  await page.getByRole('button', { name: 'New folder…' }).click()
  await dialog(page).getByRole('textbox', { name: 'Folder name' }).fill('topics')
  await dialog(page).getByRole('button', { name: 'Create' }).click()
  await expect(page).toHaveURL(`/Pi/${scratch.name}/topics`)
  await expect(node(page, `Pi/${scratch.name}/topics`)).toHaveClass(/is-selected/)
  await expect(page.getByTestId('folder-info')).toHaveText('This folder is empty.')
  expect((await stat(join(scratch.pi, 'topics'))).isDirectory()).toBe(true)
  await expect(node(page, 'Claude/subagents')).toBeVisible()
  await expect(node(page, 'Claude/subagents')).toHaveClass(/is-pinned/)
  await expect(outcome(page)).toContainText('Created folder topics')
  await expect(page.getByRole('button', { name: 'New folder…' })).toBeFocused()
})

test('Rename of the active file updates the URL and identity; it is refused while the draft is dirty', async ({ page }) => {
  const scratch = await scratchFolders()
  await writeFile(join(scratch.pi, 'old.md'), '# Old\n')
  await page.goto(`/file/Pi/${scratch.name}/old.md`)
  await editButton(page).click()
  await typeAtEnd(page, 'dirty')
  await page.getByRole('button', { name: 'Rename…' }).click()
  await expect(dialog(page)).toHaveCount(0)
  await expect(page.getByRole('alert')).toContainText(/save or discard/i)
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByTestId('save-status')).toHaveText('Saved')

  await page.getByRole('button', { name: 'Rename…' }).click()
  const name = dialog(page).getByRole('textbox', { name: 'New name' })
  await expect(name).toHaveValue('old.md')
  await name.fill('renamed.md')
  await dialog(page).getByRole('button', { name: 'Rename' }).click()
  await expect(page).toHaveURL(`/file/Pi/${scratch.name}/renamed.md`)
  await expect(page.getByRole('heading', { level: 2, name: 'renamed.md' })).toBeVisible()
  await expect(page.getByTestId('document-meta')).toContainText(`${scratch.name}/renamed.md`)
  await expect(page.getByRole('tabpanel')).toContainText('Old')
  expect(await readFile(join(scratch.pi, 'renamed.md'), 'utf8')).toBe('# Old\ndirty')
  expect(await exists(join(scratch.pi, 'old.md'))).toBe(false)
  await page.reload()
  await expect(page.getByRole('heading', { level: 2, name: 'renamed.md' })).toBeVisible()
  await page.getByRole('button', { name: 'Back to folder' }).click()
  await expect(node(page, `Pi/${scratch.name}/renamed.md`)).toBeVisible()
  await expect(node(page, `Pi/${scratch.name}/old.md`)).toHaveCount(0)
})

test('Move offers only folders of the same source and updates the active file URL; folders can be moved from the browser', async ({ page }) => {
  const scratch = await scratchFolders()
  await mkdir(join(scratch.pi, 'inbox'))
  await mkdir(join(scratch.pi, 'archive'))
  await mkdir(join(scratch.pi, 'inbox', 'empty'))
  await writeFile(join(scratch.pi, 'inbox', 'todo.md'), 'todo')
  await page.goto(`/file/Pi/${scratch.name}/inbox/todo.md`)
  await page.getByRole('button', { name: 'Move…' }).click()
  const destination = dialog(page).getByRole('combobox', { name: 'Destination folder' })
  const options = await destination.locator('option').allTextContents()
  expect(options).toContain(`${scratch.name}/archive`)
  expect(options).not.toContain(`${scratch.name}/inbox`)
  expect(options.some(option => option.includes('Claude'))).toBe(false)
  await destination.selectOption({ label: `${scratch.name}/archive` })
  await dialog(page).getByRole('button', { name: 'Move' }).click()
  await expect(page).toHaveURL(`/file/Pi/${scratch.name}/archive/todo.md`)
  await expect(page.getByTestId('document-meta')).toContainText(`${scratch.name}/archive/todo.md`)
  expect(await readFile(join(scratch.pi, 'archive', 'todo.md'), 'utf8')).toBe('todo')

  await page.getByRole('button', { name: 'Back to folder' }).click()
  await expect(page).toHaveURL(`/Pi/${scratch.name}/archive`)
  await nodeBody(page, `Pi/${scratch.name}/inbox`).click()
  await expandButton(page, 'inbox').click()
  await nodeBody(page, `Pi/${scratch.name}/inbox/empty`).click()
  await page.getByRole('button', { name: 'Move…' }).click()
  await dialog(page).getByRole('combobox', { name: 'Destination folder' }).selectOption({ label: `${scratch.name}/archive` })
  await dialog(page).getByRole('button', { name: 'Move' }).click()
  await expect(page).toHaveURL(`/Pi/${scratch.name}/archive/empty`)
  await expect(node(page, `Pi/${scratch.name}/archive/empty`)).toHaveClass(/is-selected/)
  expect(await exists(join(scratch.pi, 'archive', 'empty'))).toBe(true)
  expect(await exists(join(scratch.pi, 'inbox', 'empty'))).toBe(false)
})

test('Delete confirms with the full source and path, refuses nonempty folders, and returns to the containing folder', async ({ page }) => {
  const scratch = await scratchFolders()
  await writeFile(join(scratch.pi, 'doomed.md'), 'doomed')
  await mkdir(join(scratch.pi, 'full'))
  await writeFile(join(scratch.pi, 'full', '.hidden'), '')
  await mkdir(join(scratch.pi, 'empty'))
  await page.goto(`/file/Pi/${scratch.name}/doomed.md`)
  await page.getByRole('button', { name: 'Delete…' }).click()
  await expect(dialog(page)).toContainText('Pi')
  await expect(dialog(page)).toContainText(`${scratch.name}/doomed.md`)
  await expect(dialog(page)).toContainText('cannot be undone')
  await dialog(page).getByRole('button', { name: 'Cancel' }).click()
  await expect(dialog(page)).toHaveCount(0)
  expect(await exists(join(scratch.pi, 'doomed.md'))).toBe(true)
  await expect(page.getByRole('button', { name: 'Delete…' })).toBeFocused()

  await page.getByRole('button', { name: 'Delete…' }).click()
  await dialog(page).getByRole('button', { name: 'Delete' }).click()
  await expect(page).toHaveURL(`/Pi/${scratch.name}`)
  await expect(node(page, `Pi/${scratch.name}`)).toHaveClass(/is-selected/)
  await expect(node(page, `Pi/${scratch.name}/doomed.md`)).toHaveCount(0)
  expect(await exists(join(scratch.pi, 'doomed.md'))).toBe(false)
  await expect(outcome(page)).toContainText('Deleted doomed.md')

  await nodeBody(page, `Pi/${scratch.name}/full`).click()
  await page.getByRole('button', { name: 'Delete…' }).click()
  await dialog(page).getByRole('button', { name: 'Delete' }).click()
  await expect(dialog(page).getByRole('alert')).toContainText('not empty')
  await dialog(page).getByRole('button', { name: 'Cancel' }).click()
  expect(await exists(join(scratch.pi, 'full', '.hidden'))).toBe(true)

  await nodeBody(page, `Pi/${scratch.name}/empty`).click()
  await page.getByRole('button', { name: 'Delete…' }).click()
  await dialog(page).getByRole('button', { name: 'Delete' }).click()
  await expect(page).toHaveURL(`/Pi/${scratch.name}`)
  await expect(node(page, `Pi/${scratch.name}/empty`)).toHaveCount(0)
  expect(await exists(join(scratch.pi, 'empty'))).toBe(false)
  // Source roots offer no rename/move/delete.
  await nodeBody(page, 'Pi').click()
  await expect(page.getByRole('button', { name: 'Delete…' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Rename…' })).toBeDisabled()
})

test('Copy sends saved bytes to the other source, keeps the original open, and is labelled/disabled around drafts', async ({ page }) => {
  const scratch = await scratchFolders()
  const bytes = Buffer.from('---\r\nname: x\r\n---\r\n# Copy me\r\n', 'utf8')
  await writeFile(join(scratch.pi, 'copy.md'), bytes)
  await page.goto(`/file/Pi/${scratch.name}/copy.md`)
  await expect(page.getByRole('button', { name: 'Copy to Claude…' })).toBeVisible()
  await editButton(page).click()
  await typeAtEnd(page, 'unsaved')
  const copyButton = page.getByRole('button', { name: 'Copy saved content to Claude…' })
  await expect(copyButton).toBeVisible()

  let release: () => void = () => {}
  const held = new Promise<void>(resolve => { release = resolve })
  await page.route('**/api/file', async route => {
    if (route.request().method() !== 'PUT') return route.fallback()
    await held
    return route.fallback()
  })
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByTestId('save-status')).toHaveText('Saving')
  await expect(copyButton).toBeDisabled()
  release()
  await expect(page.getByTestId('save-status')).toHaveText('Saved')
  await typeAtEnd(page, ' more')
  await expect(copyButton).toBeEnabled()

  await copyButton.click()
  await expect(dialog(page)).toContainText('saved content')
  await expect(dialog(page)).toContainText('frontmatter')
  const destination = dialog(page).getByRole('combobox', { name: 'Destination folder' })
  const options = await destination.locator('option').allTextContents()
  expect(options).toContain(scratch.name)
  expect(options.some(option => option.includes('skills'))).toBe(false)
  await destination.selectOption({ label: scratch.name })
  await expect(dialog(page).getByRole('textbox', { name: 'File name' })).toHaveValue('copy.md')
  await dialog(page).getByRole('button', { name: 'Copy' }).click()
  await expect(dialog(page)).toHaveCount(0)
  await expect(page).toHaveURL(`/file/Pi/${scratch.name}/copy.md`)
  await expect(outcome(page)).toContainText(`Copied copy.md to Claude / ${scratch.name}/copy.md`)
  expect(await editor(page).innerText()).toContain('more')
  expect((await readFile(join(scratch.claude, 'copy.md'))).toString('hex')).toBe(Buffer.concat([bytes, Buffer.from('unsaved')]).toString('hex'))
})

test('a successful operation followed by a failed listing refresh reports both and offers Refresh, not a repeat', async ({ page }) => {
  const scratch = await scratchFolders()
  await writeFile(join(scratch.pi, 'gone.md'), 'x')
  await openGraph(page, `/Pi/${scratch.name}`)
  await nodeBody(page, `Pi/${scratch.name}/gone.md`).click()
  await expect(page).toHaveURL(`/file/Pi/${scratch.name}/gone.md`)
  await page.route('**/api/entries', route => route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ error: 'listing down' }) }))
  await page.getByRole('button', { name: 'Delete…' }).click()
  await dialog(page).getByRole('button', { name: 'Delete' }).click()
  const alert = page.getByRole('alert')
  await expect(alert).toContainText('Deleted gone.md')
  await expect(alert).toContainText('listing')
  expect(await exists(join(scratch.pi, 'gone.md'))).toBe(false)
  await expect(alert.getByRole('button', { name: 'Refresh' })).toBeVisible()
  await expect(alert.getByRole('button', { name: /Delete|Retry/ })).toHaveCount(0)
  await page.unroute('**/api/entries')
  await alert.getByRole('button', { name: 'Refresh' }).click()
  await expect(page).toHaveURL(`/Pi/${scratch.name}`)
  await expect(node(page, `Pi/${scratch.name}/gone.md`)).toHaveCount(0)
})

test('operations are keyboard accessible and usable on a narrow screen', async ({ page }) => {
  await page.setViewportSize({ width: 360, height: 640 })
  const scratch = await scratchFolders()
  await openGraph(page, `/Claude/${scratch.name}`)
  const newFile = page.getByRole('button', { name: 'New file…' })
  await newFile.focus()
  await page.keyboard.press('Enter')
  await expect(dialog(page)).toBeVisible()
  await expect(dialog(page).getByRole('textbox', { name: 'File name' })).toBeFocused()
  const box = await dialog(page).getByRole('button', { name: 'Create' }).boundingBox()
  expect(box).not.toBeNull()
  expect(box!.x + box!.width).toBeLessThanOrEqual(360)
  expect(box!.y + box!.height).toBeLessThanOrEqual(640)
  await page.keyboard.press('Escape')
  await expect(dialog(page)).toHaveCount(0)
  await expect(newFile).toBeFocused()
  await page.keyboard.press('Enter')
  await page.keyboard.type('keyboard.md')
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(`/file/Claude/${scratch.name}/keyboard.md`)
  expect(await exists(join(scratch.claude, 'keyboard.md'))).toBe(true)
  const overflow = await page.evaluate('document.documentElement.scrollWidth - document.documentElement.clientWidth')
  expect(overflow).toBe(0)
})
